

# This file was *autogenerated* from the file /Users/annina/Bachelorarbeit/Bachelorarbeit/no_interact_code2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2)
A = matrix(_sage_const_4 , _sage_const_4 , [_sage_const_1 ,_sage_const_0 ,_sage_const_1 ,_sage_const_1 ,_sage_const_1 ,_sage_const_1 ,_sage_const_1 ,_sage_const_1 ,_sage_const_0 ,_sage_const_1 ,_sage_const_0 ,_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_1 ])
b = (-_sage_const_1 )*vector([_sage_const_1 ,_sage_const_0 ,_sage_const_1 ,_sage_const_0 ])
numberOfVariables = A.ncols()
P=PolynomialRing(GF(_sage_const_2 ),A.nrows(),names="x")
(A*vector(P.gen(i) for i in range(numberOfVariables))-b).list()


